stages:
  - test

test:
  stage: test
  image: ruby:2.5
  services:
    - camunda/zeebe:0.15.1
  before_script:
    - gem install bundler
    - bundle install
  script:
    - TEST_ZEEBE=camunda-zeebe:26500 bundle exec rspec

dependency_scanning:
  stage: test
  image: docker:stable
  tags:
    - privileged
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json



# package-client:
#   stage: package
#   script:
#     - gem build hydra-upscaler-client.gemspec
# 
# package-workers:
#   stage: package
#   script:
#     - gem build hydra-upscaler-workers.gemspec
