stages:
  - test

test:
  stage: test
  services:
    - camunda/zeebe:0.15.1
  before_script:
    - bundle install
  script:
    - TEST_ZEEBE=zeebe:26500 bundle exec rspec


# package-client:
#   stage: package
#   script:
#     - gem build hydra-upscaler-client.gemspec
# 
# package-workers:
#   stage: package
#   script:
#     - gem build hydra-upscaler-workers.gemspec
